### ISSUE TITLE
Weapons can't get to +10

### ISSUE THREAD

**Issue by ChrisMuncey** [xenopiece/Dark-Souls-Dank-Random-Weapon-mod#1]
With " rand() % 10 ", you can only get upgrades from 0 to 9. It needs to be " rand() % 11 " to allow +10.

I could be overlooking something, but from what I can tell, you can't get +10.
I'm not sure if it's intentional or not, I just figured I'd point it out.

**Comment by xenopiece** [comment]
Whoops that was not intentional i guess i just brain farted when i wrote that and just went with it, thanks for bringing it to my attention.
